# Generated by Django 5.0.7 on 2024-11-04 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0006_alter_article_options_alter_tag_options'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='scope',
            constraint=models.UniqueConstraint(fields=('tag', 'article'), name='тег должен быть уникальным'),
        ),
    ]
