# Generated by Django 5.0.7 on 2024-11-04 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0007_scope_тег_должен_быть_уникальным'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scope',
            options={'verbose_name': 'связь'},
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('name',), name='такой тег уже есть'),
        ),
    ]
