# Generated by Django 5.0.7 on 2024-11-04 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0009_scope_главный_один'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='scope',
            name='главный один',
        ),
        migrations.AddConstraint(
            model_name='scope',
            constraint=models.UniqueConstraint(condition=models.Q(('is_main', True)), fields=('article', 'is_main'), name='главный один'),
        ),
    ]
